name: ACL
version: 1.4.0
description: ACL plugin for Flextype.
icon: fas fa-users-cog
author:
  name: Sergey Romanenko
  email: support@flextype.org
  url: https://flextype.org
homepage: https://github.com/flextype-plugins/acl
bugs: https://github.com/flextype-plugins/acl/issues
license: MIT

dependencies:
  flextype: 0.9.11
  twig: '>=1.0.0'
